# Generated by Django 4.0.6 on 2022-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_tag_product_created_at_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
